---
dist: trusty
sudo: required

language: c

compiler:
  - clang
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get install -y bison
  - sudo apt-get --no-install-recommends -y install texlive

script:
  - make
  - sudo make install
...
