---
dist: trusty
sudo: required

language: c

compiler:
  - clang
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get install -y bison flex automake autotools-dev
  - sudo apt-get --no-install-recommends -y install texlive texlive-luatex
  - aclocal
  - autoheader
  - autoconf
  - automake --add-missing

script:
  - ./configure
  - make
  - sudo make install
  - make distcheck
...
